DROP DATABASE IF EXISTS MVP;

CREATE DATABASE MVP;

\c MVP;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR (25) NOT NULL,
  lastName VARCHAR (25) NOT NULL,
  email VARCHAR (20) NOT NULL,
  username VARCHAR (20) NOT NULL,
  password VARCHAR (25) NOT NULL,
);

CREATE TABLE IF NOT EXISTS images (
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL,

)